### PR TITLE
⚗ Change IP addresses and streamline IP address configuration

### PR DESCRIPTION
**Pull request by Cellane**

### CODE REVIEW

**Comment by Voilane** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/Cellane/milanvit.net/93/default": exit status 1

Initializing the backend...

Successfully configured the backend "remote"! Terraform will automatically
use this backend unless the backend configuration changes.
Error refreshing state: state snapshot was created by Terraform v0.12.23, which is newer than current v0.12.19; upgrade to Terraform v0.12.23 or greater to work with this state

```

**Comment by Voilane** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # cloudflare_filter.transmission will be updated in-place
~ resource "cloudflare_filter" "transmission" {
        description = "Limit access to Portainer and Transmission to Docker network, server itself, home and office IPs"
      ~ expression  = <<~EOT
            (
              http.host in {"portainer.milanvit.net" "transmission.milanvit.net"}
              and not (
          -     ip.src in {111.98.60.102 122.218.87.26 122.218.87.66 148.251.233.134 172.17.0.0/16 183.76.253.231 2a01:4f8:201:3185::2}
          +     ip.src in {172.17.0.0/16 111.98.60.102 148.251.233.134 183.76.253.231 122.218.87.26 122.218.87.66}
                or http.request.uri.path contains "/.well-known/acme-challenge/"
              )
            )
        EOT
        id          = "6e4e0860de6a4fa2a7bcccb6e8269747"
        paused      = false
        zone_id     = "9f7f8ee361f355357f2463e64a170d0f"
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.milanvit.net/lock?id=Cellane%252Fmilanvit.net%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by Voilane** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # cloudflare_filter.transmission will be updated in-place
~ resource "cloudflare_filter" "transmission" {
        description = "Limit access to Portainer and Transmission to Docker network, server itself, home and office IPs"
      ~ expression  = <<~EOT
            (
              http.host in {"portainer.milanvit.net" "transmission.milanvit.net"}
              and not (
          -     ip.src in {111.98.60.102 122.218.87.26 122.218.87.66 148.251.233.134 172.17.0.0/16 183.76.253.231 2a01:4f8:201:3185::2}
          +     ip.src in {172.17.0.0/16 111.98.60.102 148.251.233.134 183.76.253.231 122.218.87.26 122.218.87.66}
                or http.request.uri.path contains "/.well-known/acme-challenge/"
              )
            )
        EOT
        id          = "6e4e0860de6a4fa2a7bcccb6e8269747"
        paused      = false
        zone_id     = "9f7f8ee361f355357f2463e64a170d0f"
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.milanvit.net/lock?id=Cellane%252Fmilanvit.net%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by Cellane** [comment]
atlantis help

**Comment by Voilane** [comment]
```cmake
atlantis
Terraform Pull Request Automation

Usage:
  atlantis <command> [options] -- [terraform options]

Examples:
  # run plan in the root directory passing the -target flag to terraform
  atlantis plan -d . -- -target=resource

  # apply all unapplied plans from this pull request
  atlantis apply

  # apply the plan for the root directory and staging workspace
  atlantis apply -d . -w staging

Commands:
  plan   Runs 'terraform plan' for the changes in this pull request.
         To plan a specific project, use the -d, -w and -p flags.
  apply  Runs 'terraform apply' on all unapplied plans from this pull request.
         To only apply a specific plan, use the -d, -w and -p flags.
  help   View help.

Flags:
  -h, --help   help for atlantis

Use "atlantis [command] --help" for more information about a command.
```

**Comment by Cellane** [comment]
atlantis apply

**Comment by Voilane** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
Running apply in the remote backend. Output will stream here. Pressing Ctrl-C
will cancel the remote apply if it's still pending. If the apply started it
will stop streaming the logs, but will not stop the apply running remotely.

Preparing the remote apply...

To view this run in a browser, visit:
https://app.terraform.io/app/milanvit-net/milanvit-net/runs/run-Gadmf9goddBNzGkd

Waiting for the plan to start...

Terraform v0.12.24
Configuring remote state backend...
Initializing Terraform configuration...
2020/04/10 06:06:09 [DEBUG] Using modified User-Agent: Terraform/0.12.24 TFC/0fa79e6739
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

cloudflare_zone.milanvit_net: Refreshing state... [id=9f7f8ee361f355357f2463e64a170d0f]
cloudflare_record.milanvit_net_tlsa["_143._tcp.mail"]: Refreshing state... [id=137f82db934d4cd9f6fd7a59b2461741]
cloudflare_record.milanvit_net_tlsa["_110._tcp.mail"]: Refreshing state... [id=a06a224f4697b03c9f79e4bd44edfbb2]
cloudflare_record.milanvit_net_tlsa["_465._tcp.mail"]: Refreshing state... [id=937da57a8c613b76a652b84443af730e]
cloudflare_filter.transmission: Refreshing state... [id=6e4e0860de6a4fa2a7bcccb6e8269747]
cloudflare_record.milanvit_net_tlsa["_25._tcp.mail"]: Refreshing state... [id=caf79017670339e5b198ec406ba6aec9]
cloudflare_record.milanvit_net_tlsa["_443._tcp.mail"]: Refreshing state... [id=fe954c013fdfa991c22dc3c4caeaddca]
cloudflare_record.milanvit_net_txt["carddav-srv-helper"]: Refreshing state... [id=fd78fc3d62b99998d48ee69e4cb19a97]
cloudflare_page_rule.bazarr_no_rocket_loader: Refreshing state... [id=81278a55e0e271fd64dc926bcf4c46b4]
cloudflare_record.milanvit_net_tlsa["_4190._tcp.mail"]: Refreshing state... [id=d96c8bb025f5ec11153358de228e6311]
cloudflare_record.milanvit_net_tlsa["_993._tcp.mail"]: Refreshing state... [id=6b9900f07306d5bd4c30323bf157dcb2]
cloudflare_record.milanvit_net_tlsa["_587._tcp.mail"]: Refreshing state... [id=aec3f0f54d7792a37b7ff36f27b195ec]
cloudflare_record.milanvit_net_tlsa["_995._tcp.mail"]: Refreshing state... [id=e31b6292e7b6e615b6a123b3c9ec0d97]
cloudflare_page_rule.plex_no_cache: Refreshing state... [id=8b606175cf84edc027b8e46bb6b8a033]
cloudflare_record.milanvit_net_txt["mailgun-domainkey"]: Refreshing state... [id=16dca0f203bb2dcf2a868415101e521e]
cloudflare_record.milanvit_net_txt["mailgun-spf"]: Refreshing state... [id=1fbdcd090dd86b56e0cc6066e78ca430]
cloudflare_record.milanvit_net_txt["spf"]: Refreshing state... [id=fe5b628c08cd0ea15d6539b71d57bb3e]
cloudflare_record.milanvit_net_txt["google-site-verification"]: Refreshing state... [id=f5d1a6adc8dbcafb6aacd0215d15ee26]
cloudflare_record.milanvit_net_txt["dkim"]: Refreshing state... [id=b1d3182d3abffa5ff2d666b6248dbe6d]
cloudflare_record.milanvit_net_txt["caldav-srv-helper"]: Refreshing state... [id=293dff69bf7ab0a773da1ad4bead7dfc]
cloudflare_record.milanvit_net_txt["dmarc"]: Refreshing state... [id=e0ce97e9a36b3090845b4de57c11c3b4]
cloudflare_record.milanvit_net_a["apex"]: Refreshing state... [id=59b0d533fb51c65c6e46aa08ee61ab2f]
cloudflare_record.milanvit_net_a["mail"]: Refreshing state... [id=9414a36e7890dc43596889e3924a2317]
cloudflare_record.milanvit_net_txt["keybase-site-verification"]: Refreshing state... [id=f16910d9f83f3cea20a1da4513fb1063]
cloudflare_zone_settings_override.milanvit_net: Refreshing state... [id=9f7f8ee361f355357f2463e64a170d0f]
cloudflare_record.milanvit_net_srv["submission"]: Refreshing state... [id=c93e68ca9c2f1c704cc69b60779403b0]
cloudflare_record.milanvit_net_srv["autodiscover"]: Refreshing state... [id=67a5bc147ef5cfc2d17a95ff4f80383c]
cloudflare_record.milanvit_net_srv["carddavs"]: Refreshing state... [id=df789f76c5c1a7ed4526951faefdc891]
cloudflare_record.milanvit_net_srv["imaps"]: Refreshing state... [id=4fb2e4453d49379f52322073338713c4]
cloudflare_record.milanvit_net_srv["imap"]: Refreshing state... [id=e86c20b169cb3fcc0f29326aa768b3b5]
cloudflare_record.milanvit_net_srv["sieve"]: Refreshing state... [id=5d5192d7bb0b988f3ffc35c0eed4458f]
cloudflare_record.milanvit_net_srv["pop3"]: Refreshing state... [id=f2fdeaa37b979b264f8313e70ee81476]
cloudflare_record.milanvit_net_srv["pop3s"]: Refreshing state... [id=bad7164326ee3d4be011798d054a4414]
cloudflare_record.milanvit_net_srv["smtps"]: Refreshing state... [id=413c04072fd6b714ef66047dbf412bc4]
cloudflare_record.milanvit_net_srv["caldavs"]: Refreshing state... [id=9191375a092fb814d1a72763fa580e90]
cloudflare_record.milanvit_net_mx["mailgun-1"]: Refreshing state... [id=2040a3ce02908610120985c533a9a9a6]
cloudflare_record.milanvit_net_mx["mailgun-2"]: Refreshing state... [id=a5ecc30941a963c8da98faec7298e981]
cloudflare_record.milanvit_net_mx["mail"]: Refreshing state... [id=05b89237e45757189ad3623e21304678]
cloudflare_record.milanvit_net_cname["media-plaxt"]: Refreshing state... [id=738ba61826ca8bf3ef50040d6e3c2453]
cloudflare_record.milanvit_net_cname["netdata"]: Refreshing state... [id=a150c009a5f2e2a4e44e0027372bb139]
cloudflare_record.milanvit_net_cname["media-transmission"]: Refreshing state... [id=3358a0464b4d37547687507b319c9f1c]
cloudflare_record.milanvit_net_cname["p"]: Refreshing state... [id=3af7b9994b53a63e3d64a523b1ea7d23]
cloudflare_record.milanvit_net_cname["media-tautulli"]: Refreshing state... [id=7603613693beb9a282b574cde3097cec]
cloudflare_record.milanvit_net_cname["media-radarr"]: Refreshing state... [id=70d6bde47ef1eeff5f743a18516239ce]
cloudflare_record.milanvit_net_aaaa["apex"]: Refreshing state... [id=261800c12203e65677495cad4b93fc7f]
cloudflare_record.milanvit_net_aaaa["mail"]: Refreshing state... [id=bfd604edca783243f7d8458632144335]
cloudflare_record.milanvit_net_cname["portainer"]: Refreshing state... [id=0a6d7e2e1bd82875e9d8f681bac820b9]
cloudflare_record.milanvit_net_cname["webmail"]: Refreshing state... [id=f64f9ceddf8ce8949af43ec52ff6b234]
cloudflare_record.milanvit_net_cname["newcomers"]: Refreshing state... [id=6b18bb803b73d694fb7cdba77115cb18]
cloudflare_record.milanvit_net_cname["alertmanager"]: Refreshing state... [id=c30bb3a81c529f3444302c59583f965a]
cloudflare_record.milanvit_net_cname["autodiscover"]: Refreshing state... [id=44f57870f0c4020b67b2fdb07ee67324]
cloudflare_record.milanvit_net_cname["files"]: Refreshing state... [id=d73e057cfbe89929f6321c5fad719df4]
cloudflare_record.milanvit_net_cname["media-bazarr"]: Refreshing state... [id=2fa03321f59170960e450516c19216cf]
cloudflare_record.milanvit_net_cname["office"]: Refreshing state... [id=dace2fe1821b4585a82e9d3e1141e486]
cloudflare_record.milanvit_net_cname["autoconfig"]: Refreshing state... [id=6947a49f4bc54dc1e455ad829a4116e4]
cloudflare_record.milanvit_net_cname["wildcard"]: Refreshing state... [id=50e60a70b2a7730817f01c8f3fdda2c2]
cloudflare_record.milanvit_net_cname["matomo"]: Refreshing state... [id=b0b4611fec7e454341a3d438be14b39b]
cloudflare_record.milanvit_net_cname["media-lidarr"]: Refreshing state... [id=dbee15faeb3adaccfaae2353b50244e2]
cloudflare_record.milanvit_net_cname["prometheus"]: Refreshing state... [id=608f737ae2a9826bd2d446f1cc842ee4]
cloudflare_record.milanvit_net_cname["cadvisor"]: Refreshing state... [id=ff991304dbbb3579e98ff7f4f216813c]
cloudflare_record.milanvit_net_cname["node-exporter"]: Refreshing state... [id=08f97a905f316b64a57ffa7148632457]
cloudflare_record.milanvit_net_cname["media-sonarr"]: Refreshing state... [id=27375205ba2d8d1a486f21de95b85081]
cloudflare_record.milanvit_net_cname["media-ombi"]: Refreshing state... [id=ee5b396eddc5ce401276278e8e1edfb7]
cloudflare_record.milanvit_net_cname["dmarc"]: Refreshing state... [id=acd4d8666bad7e8b3359489fc0b2c994]
cloudflare_record.milanvit_net_cname["media-jackett"]: Refreshing state... [id=f9a686f087bb7931f7be9d57bddcc1ee]
cloudflare_record.milanvit_net_cname["grafana"]: Refreshing state... [id=9af020e3b95a51bc8386d664b5411a37]
cloudflare_record.milanvit_net_cname["mail-mailgun"]: Refreshing state... [id=e6d9e4c4b7d0b4c21d6c3b75598c0a9d]
cloudflare_record.milanvit_net_caa["comodoca.com."]: Refreshing state... [id=d3934d2b5c71b9ae10115cdee1acfd1f]
cloudflare_record.milanvit_net_cname["www"]: Refreshing state... [id=bbda65643064f13c92414361b6ecf29d]
cloudflare_record.milanvit_net_cname["speedtest"]: Refreshing state... [id=1267c6106e26faac1a2c3407f668bf6d]
cloudflare_record.milanvit_net_cname["media-plex"]: Refreshing state... [id=141f1c1447e1a73e3ccd53502b639269]
cloudflare_record.milanvit_net_caa["digicert.com."]: Refreshing state... [id=fae1e1414976a484cced251ff529883c]
cloudflare_record.milanvit_net_caa["globalsign.com."]: Refreshing state... [id=0d7c0efd9ee36c32a53658b5a2aef387]
cloudflare_record.milanvit_net_caa["letsencrypt.org."]: Refreshing state... [id=fe2d56c423f7b9659422e7bf62d3172d]
cloudflare_firewall_rule.transmission: Refreshing state... [id=2f6a1068dc904d17b1e8d53d4cef7b11]

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # cloudflare_filter.transmission will be updated in-place
  ~ resource "cloudflare_filter" "transmission" {
        description = "Limit access to Portainer and Transmission to Docker network, server itself, home and office IPs"
      ~ expression  = <<~EOT
            (
              http.host in {"portainer.milanvit.net" "transmission.milanvit.net"}
              and not (
          -     ip.src in {111.98.60.102 122.218.87.26 122.218.87.66 148.251.233.134 172.17.0.0/16 183.76.253.231 2a01:4f8:201:3185::2}
          +     ip.src in {172.17.0.0/16 111.98.60.102 148.251.233.134 183.76.253.231 122.218.87.26 122.218.87.66}
                or http.request.uri.path contains "/.well-known/acme-challenge/"
              )
            )
        EOT
        id          = "6e4e0860de6a4fa2a7bcccb6e8269747"
        paused      = false
        zone_id     = "9f7f8ee361f355357f2463e64a170d0f"
    }

Plan: 0 to add, 1 to change, 0 to destroy.

cloudflare_filter.transmission: Modifying... [id=6e4e0860de6a4fa2a7bcccb6e8269747]
cloudflare_filter.transmission: Modifications complete after 0s [id=6e4e0860de6a4fa2a7bcccb6e8269747]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

nameservers = [
  "dilbert.ns.cloudflare.com",
  "lily.ns.cloudflare.com",
]
```
</details>

**Comment by Voilane** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by Voilane** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
